### PR TITLE
Addition of Customization of UILabel, UITableView, and UIBarButtonItem

### PR DESCRIPTION
**Pull request by krlnwll**
Added functions to customize UILabel, UITableView, and UIBarButtonItem

### CODE REVIEW

**Comment by mamaral** [comment]
Looks good other than in the demo the search field's accessory view toolbar background is almost the same color as the toolbar's done button. I'll merge this and tinker with it a bit so it all looks kosher. Thanks @krlnwll!

**Comment by krlnwll** [comment]
I didn't notice that, let me see if I can figure something out.

**Comment by mamaral** [comment]
I've already got a fix I'm about ready to push, I think the toolbar should probably default to the primary color, like the nav bar, so then using the secondary color of white or another lighter color will be fine.

**Comment by krlnwll** [comment]
Same thing I was doing. My intent was for when the UIBarButtonItem was in a UINavigationBar to have to take the theme.

**Comment by krlnwll** [comment]
This works as well:

+ (void)customizeBarButtonItemColor:(UIColor *)mainColor fontName:(NSString *)fontName fontSize:(CGFloat)fontSize
{
    [[UIBarButtonItem appearanceWhenContainedIn:[UINavigationBar class], nil] setTitleTextAttributes:@{NSFontAttributeName:[UIFont fontWithName:fontName size:fontSize],
                                                                                                       NSForegroundColorAttributeName:mainColor}
                                                                                            forState:UIControlStateNormal];
}

**Comment by mamaral** [comment]
https://github.com/mamaral/MAThemeKit/commit/3fbca31443961045b918fee22578580080635166 Fixes that issue. Thanks again! Contribute anytime!

**Pull request merged**
